// pipeline {
//   agent any
//   tools {
//     nodejs '22.4.1'
//   }

//   options {
//     timeout(time: 2, unit: 'MINUTES')
//   }

//   stages {
//     stage('Install dependencies') {
//       steps {
//         sh 'cd jenkins-tests && npm i'
//       }
//     }
//     stage('Run tests') {
//       steps {
//         sh 'cd jenkins-tests && npm test'
//       }
//     }
//   }
// }


pipeline {
  agent any
  tools {
    nodejs '22.4.1'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm install'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && ./node_modules/.bin/mocha'
      }
    }
  }
}
